import type { BrandTokens } from '../brand/presets.js';

/** Write assets/brand-tokens.css from resolved brand tokens. */
export function generateBrandTokensCss(brand: BrandTokens): string {
  return `/* Auto-generated by pipeline — do not edit manually */
:root {
  --brand-bg: ${brand.background};
  --brand-accent: ${brand.accent};
  --brand-accent-secondary: ${brand.accentSecondary};
  --brand-text: ${brand.text};
  --brand-text-dim: ${brand.textDim};
  --brand-surface: ${brand.surface};
  --brand-font-display: ${brand.fontDisplay};
  --brand-font-mono: ${brand.fontMono};
}
`;
}
